package shop.entities;
// Generated Apr 21, 2018 4:25:32 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "shop")
public class Product implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "productID", unique = true, nullable = false)
	private long productId;
	@Column(name = "decription")
	private String decription;
	@Column(name = "imageID")
	private Long imageId;
	@Column(name = "productName")
	private String productName;
	@Column(name = "Price", precision = 10)
	private Double price;
	@OneToOne()
	@JoinColumn(name = "category")
	private Category category;
	@Column(name = "productState")
	private String productState;

	public Product() {
	}

	public Product(long productId) {
		this.productId = productId;
	}

	public Product(long productId, String decription, Long imageId, String productName, Double price, Category category,
			String productState) {
		this.productId = productId;
		this.decription = decription;
		this.imageId = imageId;
		this.productName = productName;
		this.price = price;
		this.category = category;
		this.productState = productState;
	}

	public long getProductId() {
		return this.productId;
	}

	public void setProductId(long productId) {
		this.productId = productId;
	}

	public String getDecription() {
		return this.decription;
	}

	public void setDecription(String decription) {
		this.decription = decription;
	}

	public Long getImageId() {
		return this.imageId;
	}

	public void setImageId(Long imageId) {
		this.imageId = imageId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getProductState() {
		return this.productState;
	}

	public void setProductState(String productState) {
		this.productState = productState;
	}

}
